In [2]:
import numpy as np

1) Из существуюущих данных в Python

In [29]:
# from the list

list_1=[1,2,3,4]
list_2=[[1,2,3],[4,5,6]]
a=np.array(list_1)
b=np.array(list_2)

a,b

(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [30]:
#from the tuple

tuple_=(1,2,3,4)
arr=np.array(tuple_)
arr

array([1, 2, 3, 4])

In [ ]:
# Parameters ndarray

#dtype
a=np.array([1,2,3], dtype=np.float64)
a, a.dtype

b=np.array([1.4, 2.33, 4.44], dtype=np.int32)
b, b.dtype


# copy (by default - True)
a=np.array([1,2,3])
a
c=np.array(a, copy=False) # creating view
c is a


#ndmin
d=np.array([1,2,3], ndmin=2)
d.shape # (1,3), not (3,)

(1, 3)

In [16]:
# np.asarray() - by default, it does not copy data.

a=np.array([1,2,3])
b=np.asarray(a)
b is a

True

2) Массивы заполненные константами

In [ ]:
# zeros
np.zeros(5)
np.zeros((2,3))
np.zeros((2,3,4))

#ones
np.ones(4)
np.ones((2,3))
np.ones((2,3,3))


#full
np.full(5,4)
np.full((2,3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [42]:
#empty()

np.empty((3,4))

result=np.empty(100)
for i in range(100):
    result[i]=i*2

result

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100., 102., 104., 106., 108.,
       110., 112., 114., 116., 118., 120., 122., 124., 126., 128., 130.,
       132., 134., 136., 138., 140., 142., 144., 146., 148., 150., 152.,
       154., 156., 158., 160., 162., 164., 166., 168., 170., 172., 174.,
       176., 178., 180., 182., 184., 186., 188., 190., 192., 194., 196.,
       198.])

In [41]:
# _like 

a=np.array([[1,2,3],[4,5,6]]) #shape=(2,3), dtype=int64

np.zeros_like(a)
np.ones_like(a)
np.full_like(a, 9)
np.empty_like(a)



array([[9, 9, 9],
       [9, 9, 9]])

3) Диапазоны и последовательности

In [7]:
# np.arrange()

np.arange(5)
np.arange(0,11,2)
np.arange(10,0,-1)
np.arange(0,2,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [13]:
# np.linspace()

np.linspace(0,1,5)
np.linspace(1,10,11)
#endpoint=True
np.linspace(0,1,5, endpoint=False)

#retstep - return step
arr, step=np.linspace(0,2,10, retstep=True)

In [32]:
#np.logspace()

np.logspace(0, 4, 4)
np.logspace(0, 1, 5)


array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [31]:
# np.geomspace()

np.geomspace(2, 32, 5)

array([ 2.,  4.,  8., 16., 32.])