In [44]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a.dtype, a.dtype.name, a.itemsize

(dtype('int64'), 'int64', 8)

Строки в ndarray

In [ ]:
#unicode-strings
a = np.array(['hello', 'world'])
a.dtype 
b = np.array(['cat', 'elephant'])
b.dtype


#byte-strings
bs = np.array([b'dog', b'cat'])
bs.dtype


#objects
obj = np.array(['ат', 1212.2, [12,122,'xcvs']], dtype = object)
obj.dtype


dtype('O')

In [15]:
#data types by default
np.array([1,2,3]).dtype
np.array([1.0, 2.0]).dtype
np.array([1, 2, 3.0]).dtype
np.array([1, 2, 'a']).dtype

np.array([2.9, 5, 3], dtype='int32')

np.ones((2,4), dtype=np.bool_)

np.full((9,12), 12, dtype='f4')

array([[12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.]],
      dtype=float32)

Переобразование типа - astype()

In [23]:
a=np.array([1, 2, 3, 4])

b=a.astype(np.float32)
b
c=a.astype(np.bool_)
c

e = np.array([1.7, 2.3, 5.9])
e.astype(np.int32)

f = np.array(['1', '2', '3'])
f.astype('int8')




array([1, 2, 3], dtype=int8)

In [27]:
#overflow 

a = np.array([30], dtype='int8') #300 - 256 = 44 


b = np.array([127], dtype='int8')
b+1

array([-128], dtype=int8)

How to choose the right type

In [35]:
# images - pixels 0-255
image = np.array([10,20,30], dtype='uint8')
image

# machine learning - float32(standart)
weights=np.random.randn(10,10).astype('float32')

#masks & flags 
mask = np.array([1, 0, 1, 1], dtype='bool_')
mask


#counters, indexes
indices = np.arange(1000, dtype=np.int32)


#finance, high precision
prices = np.array([2320.232, 2234.2232], dtype = 'float64')



In [41]:
#Проверка и сравнение типов

a = np.array([1, 2, 3])
a.dtype == 'int64'

np.issubdtype(a.dtype, np.integer)
np.issubdtype(a.dtype, np.floating)
np.issubdtype(a.dtype, np.number)

True

In [56]:
#dtype - this is object
a= np.array([1, 3, 4])
np.dtype('float32')

isinstance(np.dtype(np.int8), np.dtype)
type(np.int8)


type